---
fixtures:
  forge_modules:
    concat: 
        repo: "puppetlabs/concat"
        ref : "7.1.1"
    stdlib: 
        repo: "puppetlabs/stdlib"
        ref : "8.5.0"
    xinetd: 
        repo: "puppetlabs/xinetd"
        ref : "3.3.0"
    systemd:
        repo: "puppet/systemd"
        ref: "3.10.0"
  repositories: {}
  symlinks:
    remctl: "#{source_dir}"
